### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: Invalid reference index -1

### ISSUE THREAD

**Issue by robinycfang** [epifluidlab/FinaleMe#4]
Hi thanks for the great tool!

I am trying to run it with hg38. I have converted the correpsonding files to hg38 and ran followings, but got the error below. Not sure what is going on...

2bit of hg38 was downloaded from ucsc
cpgIslandExt.hg38.ucsc.bed has 3 cols, chr start and end
wgbs_buffyCoat_jensen2015GB.methy.hg38.bw.bw was lifted over from wgbs_buffyCoat_jensen2015GB.methy.hg19.bw

also, if i want to work on CRAM file, can you point me the line where i can add a parameter for that?

Thanks!!!

```
java -Xmx20G -cp "target/FinaleMe-0.58-jar-with-dependencies.jar:lib/gatk-package-distribution-3.3.jar:lib/sis-jhdf5-batteries_included.jar:lib/java-genomics-io.jar:lib/igv.jar" \
> org.cchmc.epifluidlab.finaleme.utils.CpgMultiMetricsStats \
> ref/hg38.2bit \
> ref/cpg/cpgIslandExt.hg38.ucsc.bed \
> ref/cpg/cpgIslandExt.hg38.ucsc.bed \
> test/test_bam/PANX_1405_Ly_R_401NS_0.01x.bam \
> test/finaleme/CpgMultiMetricsStats.hg38.details.bed.gz \
> -stringentPaired \
> -excludeRegions ref/mappability/ENCFF356LFX_ENCODE_Unified_GRCh38_Exclusion_List.bed \
> -valueWigs methyPrior:0:ref/bw/wgbs_buffyCoat_jensen2015GB.methy.hg38.bw.bw \
> -wgsMode
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:tools/FinaleMe/target/FinaleMe-0.58-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:tools/FinaleMe/lib/gatk-package-distribution-3.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
INFO [2024-04-23 00:30:24,582]  [CpgMultiMetricsStats.java:192] [main]  Processing interval file ... 
INFO [2024-04-23 00:30:24,627]  [CpgMultiMetricsStats.java:199] [main]  Excluding intervals ... 
INFO [2024-04-23 00:30:24,637]  [CpgMultiMetricsStats.java:407] [main]  Loading value interval big wig file ...
INFO [2024-04-23 00:30:24,816]  [CpgMultiMetricsStats.java:437] [main]  Automate generate all k-mer until length 0
INFO [2024-04-23 00:30:24,816]  [CpgMultiMetricsStats.java:482] [main]  Loading CpG interval file ...
INFO [2024-04-23 00:30:24,898]  [CpgMultiMetricsStats.java:536] [main]  Get total reads number used for scaling from bam file... 
INFO [2024-04-23 00:30:26,471]  [CpgMultiMetricsStats.java:554] [main]  351402 reads in total ...
INFO [2024-04-23 00:30:26,472]  [CpgMultiMetricsStats.java:556] [main]  Output value for each CpG in each DNA fragment ...
Exception in thread "main" java.lang.IllegalArgumentException: Invalid reference index -1
        at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:503)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:365)
        at org.cchmc.epifluidlab.finaleme.utils.CpgMultiMetricsStats.doMain(CpgMultiMetricsStats.java:598)
        at org.cchmc.epifluidlab.finaleme.utils.CpgMultiMetricsStats.main(CpgMultiMetricsStats.java:144)
```

**Comment by robinycfang** [comment]
problem solved, I added 4th column to cpgIslandExt.hg38.ucsc.bed with a value of 1
