### ISSUE TITLE
STEP1 ：Exception in thread "main" java.lang.IllegalArgumentException: Invalid reference index -1

### ISSUE THREAD

**Issue by pei-wang111** [epifluidlab/FinaleMe#5]
Hi, 
I am trying to run your code. but I get an error in step 1:
Exception in thread "main" java.lang.IllegalArgumentException: Invalid reference index -1
        at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:503)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:365)
        at org.cchmc.epifluidlab.finaleme.utils.CpgMultiMetricsStats.doMain(CpgMultiMetricsStats.java:598)
        at org.cchmc.epifluidlab.finaleme.utils.CpgMultiMetricsStats.main(CpgMultiMetricsStats.java:144)

I run it with the following code:
samtools sort -o BH01.chr22.sorted.bam BH01.chr22.bam
samtools index BH01.chr22.sorted.bam
java -Xmx20G -cp "target/FinaleMe-0.58-jar-with-dependencies.jar:lib/gatk-package-distribution-3.3.jar:lib/sis-jhdf5-batteries_included.jar:lib/java-genomics-io.jar:lib/igv.jar" org.cchmc.epifluidlab.finaleme.utils.CpgMultiMetricsStats files/hg19.2bit files/CG_motif.hg19.common_chr.pos_only.bedgraph files/CG_motif.hg19.common_chr.pos_only.bedgraph files/BH01.chr22.sorted.bam CpgMultiMetricsStats.hg19.details.bed.gz -stringentPaired -excludeRegions files/wgEncodeDukeMapabilityRegionsExcludable_wgEncodeDacMapabilityConsensusExcludable.hg19.bed -valueWigs methyPrior:0:files/wgbs_buffyCoat_jensen2015GB.methy.hg19.bw -wgsMode

wgEncodeDukeMapabilityRegionsExcludable_wgEncodeDacMapabilityConsensusExcludable.hg19.bed,wgbs_buffyCoat_jensen2015GB.methy.hg19.bw are provided in the tutorial. hg19.2bit downloaded from UCSC, the content of CG_motif.hg19.common_chr.pos_only.bedgraph file is as follows:

chr22   16122622        16122923
chr22   16155753        16158017
chr22   16192654        16193098
chr22   16200149        16200707
chr22   16217287        16217676
chr22   16228205        16228546
chr22   16288314        16288570
chr22   16374539        16374899
chr22   16404342        16404671
chr22   16423842        16424117
......

Can you please help me?

**Comment by pei-wang111** [comment]
I have resolved the issue already, still, thank you.
